# hotel-ops-api/.github/workflows/backend.yml

name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Use Node.js 18
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Run tests (and provide OPENAI_API_KEY from Secrets)
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm test
